// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgVIl_yfmXl8o-XCrkbyYAwTUBAnAZZ_c',
    appId: '1:573229922917:web:592b80a370a0ce6e42248c',
    messagingSenderId: '573229922917',
    projectId: 'servifino',
    authDomain: 'servifino.firebaseapp.com',
    storageBucket: 'servifino.firebasestorage.app',
    measurementId: 'G-XB52G96H7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA51ivw-Jkuf9Fb_MRkGn_Ds2jnn7JXR68',
    appId: '1:573229922917:android:0c7fbe813929a6d242248c',
    messagingSenderId: '573229922917',
    projectId: 'servifino',
    storageBucket: 'servifino.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSb4eozkz-M6bx1_Sd65TmhQT7b7I6tUI',
    appId: '1:573229922917:ios:2ae8da9e93ca557f42248c',
    messagingSenderId: '573229922917',
    projectId: 'servifino',
    storageBucket: 'servifino.firebasestorage.app',
    iosBundleId: 'dev.savinofiore.servifino.servifino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSb4eozkz-M6bx1_Sd65TmhQT7b7I6tUI',
    appId: '1:573229922917:ios:2ae8da9e93ca557f42248c',
    messagingSenderId: '573229922917',
    projectId: 'servifino',
    storageBucket: 'servifino.firebasestorage.app',
    iosBundleId: 'dev.savinofiore.servifino.servifino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgVIl_yfmXl8o-XCrkbyYAwTUBAnAZZ_c',
    appId: '1:573229922917:web:0caef9b27c27cef542248c',
    messagingSenderId: '573229922917',
    projectId: 'servifino',
    authDomain: 'servifino.firebaseapp.com',
    storageBucket: 'servifino.firebasestorage.app',
    measurementId: 'G-R1JLYPHSE3',
  );
}
